# Generated by Django 3.0.6 on 2020-05-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_me_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
