# Generated by Django 3.0.6 on 2020-05-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_auto_20200518_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='me',
            old_name='body2',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='me',
            name='body1',
        ),
    ]
